name: appleshop
networks:
    app-network:
        driver: bridge

services:
  assets-server:
    image: lolmobi495/doan:assets-server
    #restart: always
    pull_policy: always
    container_name: assets-server-php
    ports:
      - "1009:8081"
    volumes:
      - ./docker/certs:/https
      - ./docker/settings/appsettings.json:/app/appsettings.json
      - ./docker/assets:/app/wwwroot/assets
    env_file:
      - ./docker/net.env
    networks:
      - app-network

  php-apache:
      image: php:8.1-fpm
      container_name: php-apache
      working_dir: /var/www
      volumes:
          - ./AppleShop:/var/www
      networks:
          - app-network
      environment:
          - APACHE_DOCUMENT_ROOT=/var/www/public
      command: /bin/sh -c "docker-php-ext-install pdo pdo_mysql && php-fpm -F"

  nginx:
      image: nginx:alpine
      container_name: nginx
      working_dir: /var/www
      volumes:
          - ./AppleShop:/var/www
          - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - "8000:80"
      networks:
          - app-network

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    environment:
      - SWAGGER_JSON=/swagger/swagger.json
    volumes:
      - ./AppleShop/storage/api-docs:/swagger
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hht_appleshop
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./docker/data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network
