name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      SERVICES: appleshop
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker images using Docker Compose
      - name: Build Docker Images
        run: |
          cd .\AppleShop\
          docker build -t lolmobi495/doan:appleshop .

      # Push Docker images to Docker Hub
      - name: Push Docker Images
        run: |
          echo "${{ secrets.ACTION }}" | docker login -u lolmobi495 --password-stdin
          services=($SERVICES)
          for service in "${services[@]}"; do
            docker push lolmobi495/doan:"${service}"
          done

      # Prune unused Docker images
      - name: Remove unused Docker images
        run: docker image prune -f