name: Create Pull Request, Merge, and Build Docker

on:
  push:
    branches:
      - sub

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Step 1: Checkout repository to work with sub branch
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Create Pull Request from sub to main
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: main
          delete-branch: false
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/hungg523
          labels: |
            automated pr
          milestone: 1
          draft: false

  build-and-push:
    runs-on: ubuntu-latest
    needs: create-pull-request
    if: success()
    env:
      SERVICES: appleshop
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lolmobi495
          password: ${{ secrets.ACTION }}

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Build Docker images using Docker Buildx with caching
      - name: Build Docker Images with Caching
        uses: docker/build-push-action@v5
        with:
          context: ./AppleShop
          tags: lolmobi495/doan:appleshop
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      # Push Docker images to Docker Hub
      - name: Push Docker Images
        uses: docker/build-push-action@v5
        with:
          context: ./AppleShop
          push: true
          tags: lolmobi495/doan:appleshop
      
      # Prune Docker builder cache
      - name: Prune Docker builder cache
        run: docker builder prune -f

      # Prune unused Docker images
      - name: Remove unused Docker images
        run: docker image prune -f
